# Generated by Django 2.2 on 2020-07-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0004_auto_20200720_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
