# Generated by Django 2.2 on 2020-07-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0006_auto_20200720_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
