# Generated by Django 2.2 on 2020-07-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0008_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
